# DataSonnet Header

The header is an optional comment section in the mapping document which must start with `/\** DataSonnet` followed by a new line character and end with a line `*/` and contains a set of configuration properties.
The properties are hierarchical, with sections separated by the `.` (dot) character, e.g.:

------------
dataformat.application/xml.payload.NamespaceSeparator=:
dataformat.application/xml.payload.TextValueKey=__text
dataformat.application/csv.myVar.Quote="
dataformat.application/csv.myVar.Separator=|
------------

The header must be the first comment before any other line of code, in the following format:

-------------
/** DataSonnet
version=<VERSION_NUMBER>
<PROPERTY>=<VALUE>
...
*/
-------------
*Example*
------------------------
/** DataSonnet
version=1.0
*/
//DataSonnet mapping starts here
{
    mappedValue: payload.value
}
------------------------

The header is optional; if omitted, all default settings will be used.

## Data Format Properties

The data format properties control the data format plugins behavior. The property names must start with `dataformat.<MIME_TYPE>.payload|output|*|<VAR_NAME>` where `<MIME_TYPE>` is the mime type supported by the DataSonnet. If a property is not recognized, an error will be raised.

IMPORTANT: if the mime type contains the dot (`.`) character, it must be escaped with double backslash (`\\`). For example, `dataformat.application/vnd\\.ms-excel.payload.param=xyz`.

The wildcard `*` can be used to set the same parameter value for all inputs and output of the given format, instead of defining it explicitly. For example:

------------
dataformat.application/csv.*.Separator=|
------------

is an equivalent of:

------------
dataformat.application/csv.payload.Separator=|
dataformat.application/csv.myVar.Separator=|
dataformat.application/csv.output.Separator=|
------------

An explicit setting will override the wildcard setting for a specific input or output. For example, if there are multiple CSV inputs that have separator `|` except one that has separator `,`, the following configuration can be used:

------------
dataformat.application/csv.*.Separator=|
dataformat.application/csv.commaSeparatedVar.Separator=,
------------

For the list of the supported data formats and their configurable properties, see the xref:dataformats.adoc[Data Formats] section.







