# DataSonnet Libraries
:toc:
:toclevels: 1

## core

### `append(array arr, any val)`
Given `arr` and `val`, appends `val` to the end of `arr`.

*Example*

.Payload
----------
[
    2,
    3,
    5,
    7
]
----------
.DataSonnet map:
------------------------
ds.append(payload, 11)
------------------------
.Result
------------------------
[
  2,
  3,
  5,
  7,
  11
]
------------------------

### `combine(any first, any second)`
Combines `first` and `second`. Some values will auto-coerce, e.g. the number 5 will auto coerce to the string "5."

*Example*

.DataSonnet map:
------------------------
{
    string: ds.combine("Hello ", "World"),
    number: ds.combine(5, 7),
    auto1: ds.combine("Hello ", 5),
    auto2: ds.combine(5, "10"),
    array: ds.combine([1,2], [3,4]),
    obj: ds.combine({a:1}, {b:2})
}
------------------------
.Result
------------------------
{
  "string": "Hello World",
  "number": "57",
  "auto1": "Hello 5",
  "auto2": "510",
  "array": [
    1,
    2,
    3,
    4
  ],
  "obj": {
    "a": 1,
    "b": 2
  }
}
------------------------

### `contains(array|string item, any val)`
If `item` is an array, returns true if `item` contains `val`.

If `item` is a string, returns true if `item` contains the sub string `val`.

*Example*

.Payload
----------
[
    2,
    3,
    5,
    7
]
----------
.DataSonnet map:
------------------------
ds.contains(payload, 2)
------------------------
.Result
------------------------
true
------------------------

### `distinctBy(array|object item, function discriminator)`
Returns a new object containing only the items that are a unique result from `discriminator`.

The function `discriminator` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
{
  "array": [
    1,
    1,
    2,
    2,
    3,
    3,
    4,
    4,
    5
  ],
  "obj": {
    "a": 1,
    "b": 2,
    "c": 1
  }
}
----------
.DataSonnet map:
------------------------
{
    array: ds.distinctBy(payload.array, function(item,index) item),
    obj: ds.distinctBy(payload.obj, function(value,key) value)
}
------------------------
.Result
------------------------
{
  "array": [
    1,
    2,
    3,
    4,
    5
  ],
  "obj": {
    "a": 1,
    "b": 2
  }
}
------------------------

### `endsWith(string str, string subStr)`
Returns true if `str` ends with `subStr`. Ignores casing.

*Example*

.Payload
----------
{
    "name": "Scala",
    "version": "1.0"
}
----------
.DataSonnet map:
------------------------
ds.endsWith(payload.version, ".0")
------------------------
.Result
------------------------
true
------------------------

### `entriesOf(object obj)`
Returns an array of objects describing each key value pair of `obj`.

*Example*

.Payload
----------
{
    "name": "Scala",
    "version": "1.0"
}
----------
.DataSonnet map:
------------------------
ds.entriesOf(payload)
------------------------
.Result
------------------------
[
  {
    "value": "Scala",
    "key": "name"
  },
  {
    "value": "1.0",
    "key": "version"
  }
]
------------------------

### `filter(array arr, function func)`
Filters `arr` depending on the result of `func`.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.filter(payload, function(value, index) value < 3)
------------------------
.Result
------------------------
[
  1,
  2
]
------------------------

### `filterObject(object obj, function func)`
Filters `obj` depending on the result of `func`.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
    "version": 1.7
}
----------
.DataSonnet map:
------------------------
ds.filterObject(payload, function(value, key, index) value > 1.5)
------------------------
.Result
------------------------
{
  "version": 1.7
}
------------------------

### `find(string|array item, any val)`
Returns an array containing the location where `val` occurs in `item`.

*Example*

.Payload
----------
{
    "string": "Hello World",
    "array": [1,2,3,4]
}
----------
.DataSonnet map:
------------------------
{
    string: ds.find(payload.string, "World"),
    array: ds.find(payload.array, 3)
}
------------------------
.Result
------------------------
{
  "string": [6],
  "array": [2]
}
------------------------

### `flatten(array arr)`
Given `arr`, which contains one level arrays, creates a flat array.

*Example*

.Payload
----------
[
  [
    1,
    2
  ],
  [
    3,
    4
  ]
]
----------
.DataSonnet map:
------------------------
ds.flatten(payload)
------------------------
.Result
------------------------
[
  1,
  2,
  3,
  4
]
------------------------

### `flatMap(array arr, function func)`
Given an array of arrays `arr`, creates a flat array using the outcome of `func`.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
    [
        2,
        3,
        5,
        7
    ],
    [
        11,
        13,
        17,
        19
    ]
]
----------
.DataSonnet map:
------------------------
ds.flatMap(payload, function(value, index) value)
------------------------
.Result
------------------------
[
  2,
  3,
  5,
  7,
  11,
  13,
  17,
  19
]
------------------------

### `foldLeft(array arr, function func, any initVal)`
Iterates over `arr`, applying `func` to the previous result. Starts with the value provided in `initVal`.

The function `func` is expected to take the current value as the first parameter (required) and the previous value as the second parameter (required).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.foldLeft(payload, function(curr, prev) curr * prev, 1)
------------------------
.Result
------------------------
24
/*
  1 * 1 = 1
  2 * 1 = 2
  3 * 2 = 6
  4 * 6 = 24
*/
------------------------

### `foldRight(array arr, function func, any initVal)`
Iterates backwards over an array, applying `func` to the previous result. Starts with the value provided in `initVal`.

The function `func` is expected to take the current value as the first parameter (required) and the previous value as the second parameter (required).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.foldRight(payload, function(curr, prev) curr * prev, 1)
------------------------
.Result
------------------------
24
/*
  4 * 1 = 4 // 1 in this case is the initial value
  3 * 4 = 12
  2 * 12 = 24
  1 * 24 = 24
*/
------------------------

### `groupBy(array|object items, function discriminator)`
Groups the provided `items` into an object based on the result of `discriminator`.

The function `discriminator` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
{
    "array": [
        "a",
        "b",
        "a"
    ],
    "obj": {
        "a":"Alpha",
        "b":"Bravo",
        "c": "Alpha"
    }
}
----------
.DataSonnet map:
------------------------
{
    array: ds.groupBy(payload.array, function(item,index) item ),
    obj: ds.groupBy(payload.obj, function(value,key) value)
}
------------------------
.Result
------------------------
{
  "array": {
    "a": [
      "a",
      "a"
    ],
    "b": [
      "b"
    ]
  },
  "obj": {
    "Alpha": {
      "a": "Alpha",
      "c": "Alpha"
    },
    "Bravo": {
      "b": "Bravo"
    }
  }
}
------------------------

### `isArray(any valToCheck)`
Accepts any given value as `valToCheck` and checks if it is of type array.

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.isArray(payload)
------------------------
.Result
------------------------
true
------------------------

### `isBlank(string strToCheck)`
Checks if `strToCheck` is blank. Also returns true if null.

*Example*

.DataSonnet map:
------------------------
{
    str1: ds.isBlank("     "),
    str2: ds.isBlank(""),
    'null': ds.isBlank(null)
}
------------------------
.Result
------------------------
{
  "str1": true,
  "str2": true,
  "null": true
}
------------------------

### `isBoolean(any valToCheck)`
Accepts any given value as `valToCheck` and checks if it is of type bool.

*Example*

.Payload
----------
{
  "name": "Java",
  "isObjectOriented": true
}
----------
.DataSonnet map:
------------------------
ds.isBoolean(payload.isObjectOriented)
------------------------
.Result
------------------------
true
------------------------

### `isDecimal(num numToCheck)`
Checks that the input number `numToCheck` is a decimal number. Trailing zeros are ignored.

*Example*

.DataSonnet map:
------------------------
{
    a: ds.isDecimal(2),
    b: ds.isDecimal(2.0),
    c: ds.isDecimal(2.1),
}
------------------------
.Result
------------------------
{
  "a": false,
  "b": false,
  "c": true
}
------------------------

### `isEmpty(any valToCheck)`
Checks if `valToCheck` is empty. Does not ignore white space if string. Returns true if null.

*Example*

.DataSonnet map:
------------------------
{
    "null": ds.isEmpty(null),
    str: ds.isEmpty("    "),
    array: ds.isEmpty([]),
    obj: ds.isEmpty({})
}
------------------------
.Result
------------------------
{
  "null": true,
  "str": false,
  "array": true,
  "obj": true
}
------------------------

### `isEven(num numToCheck)`
Checks that the input number `numToCheck` is an even number.

*Example*

.Payload
----------
{
    "version": 2.0
}
----------
.DataSonnet map:
------------------------
ds.isEven(payload.version)
------------------------
.Result
------------------------
true
------------------------

### `isFunction(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type function.

*Example*

.DataSonnet map:
------------------------
ds.isFunction(function() "5")
------------------------
.Result
------------------------
true
------------------------

### `isInteger(num numToCheck)`
Checks that the input number `numToCheck` is an integer. Trailing zeros are ignored.

*Example*

.Payload
----------
{
    "version": 2.0
}
----------
.DataSonnet map:
------------------------
ds.isInteger(payload.version)
------------------------
.Result
------------------------
true
------------------------

### `isNumber(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type number.

*Example*

.Payload
----------
{
    "age": 5
}
----------
.DataSonnet map:
------------------------
ds.isNumber(payload.age)
------------------------
.Result
------------------------
true
------------------------

### `isObject(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type object.

*Example*

.Payload
----------
{
    "language": "Java"
}
----------
.DataSonnet map:
------------------------
ds.isObject(payload)
------------------------
.Result
------------------------
true
------------------------

### `isOdd(num numToCheck)`
Checks that `numToCheck` is an odd number.

*Example*

.Payload
----------
{
    "age": 5
}
----------
.DataSonnet map:
------------------------
ds.isOdd(payload.age)
------------------------
.Result
------------------------
true
------------------------

### `isString(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type string.

*Example*

.Payload
----------
{
    "language":"Java"
}
----------
.DataSonnet map:
------------------------
ds.isString(payload.language)
------------------------
.Result
------------------------
true
------------------------

### `joinBy(array arr, string separator)`
Joins `arr` into a string with the provided `separator`.

*Example*

.Payload
----------
{
    "versions": [1.0, 1.2, 1.7, 1.8]
}
----------
.DataSonnet map:
------------------------
ds.joinBy(payload.versions, ", ")
------------------------
.Result
------------------------
"1, 1.2, 1.7, 1.8"
------------------------

### `keysOf(object obj)`
Returns an array of all the key names in `obj`.

*Example*

.Payload
----------
{
   "departureDate": "01/20/2019",
   "origin": "PHX",
   "destination": "SEA"
 }
----------
.DataSonnet map:
------------------------
ds.keysOf(payload)
------------------------
.Result
------------------------
[
  "departureDate",
  "origin",
  "destination"
]
------------------------

### `lower(string str)`
Converts `str` to all lower case characters.

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
 }
----------
.DataSonnet map:
------------------------
ds.lower(payload.origin)
------------------------
.Result
------------------------
"phx"
------------------------

### `map(array arr, function func)`
Loops through all items in `arr`, applies `func` to each, and returns a new array containing each result. Returns null if `arr` is null.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
{
    "versions": [1.0, 1.2, 1.7, 1.8]
}
----------
.DataSonnet map:
------------------------
ds.map(payload.versions, function(value, index) value > 1.2)
------------------------
.Result
------------------------
[
  false,
  false,
  true,
  true
]
------------------------

### `mapEntries(object obj, function func)`
Loops through all properties in `obj`, applies `func` to each, and returns a new array containing each result.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
}
----------
.DataSonnet map:
------------------------
ds.mapEntries(payload, function(value, key, index) value)
------------------------
.Result
------------------------
[
  "PHX",
  "SEA"
]
------------------------

### `mapObject(object obj, function func)`
Loops through all properties in `obj`, applies `func` to each, and returns a new object containing each result.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
}
----------
.DataSonnet map:
------------------------
ds.mapObject(payload, function(value, key, index) {[key]:value})
------------------------
.Result
------------------------
{
  "origin": "PHX",
  "destination": "SEA"
}
------------------------

### `match(string str, string regex)`
Executes the regex expression `regex` against `str` and returns an array with the match groups.

*Example*

.Payload
----------
{
    "email": "test@server.com"
}
----------
.DataSonnet map:
------------------------
ds.match(payload.email, "(.*)@(.*)(.com)")
------------------------
.Result
------------------------
[
  "test@server.com",
  "test",
  "server",
  ".com"
]
------------------------

### `matches(string str, string regex)`
Executes the regex expression `regex` against `str` and returns `true` or `false` if the expression matches the input.

*Example*

.Payload
----------
{
    "email": "test@server.com"
}
----------
.DataSonnet map:
------------------------
ds.matches(payload.email, "(.*)@(.*)(.com)")
------------------------
.Result
------------------------
true
------------------------

### `max(array arr)`
Returns the max value in `arr`.

*Example*

.Payload
----------
[
    5,
    2,
    7,
    3
]
----------
.DataSonnet map:
------------------------
ds.max(payload)
------------------------
.Result
------------------------
7
------------------------

### `maxBy(array arr, function func)`
Returns the max result of `func` in `arr`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.maxBy(payload, function(value) value.age)
------------------------
.Result
------------------------
{
  "age": 7
}
------------------------

### `min(array arr)`
Returns the min value in `arr`.

*Example*

.Payload
----------
[
    5,
    2,
    7,
    3
]
----------
.DataSonnet map:
------------------------
ds.min(payload)
------------------------
.Result
------------------------
2
------------------------

### `minBy(array arr, function func)`
Returns the max result of `func` in `arr`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.minBy(payload, function(value) value.age)
------------------------
.Result
------------------------
{
  "age": 3
}
------------------------

### `orderBy(array|object items, function func)`
Reorders the array `items` by the result of `func`.

If `items` is an array: the function `func` is expected to take the value as the first parameter (required).

If `items` is an object: the function `func` is expected to take the value as the first parameter (required) and the key as the second parameter (optional).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.orderBy(payload, function(value) value.age)
------------------------
.Result
------------------------
[
  {
    "age": 3
  },
  {
    "age": 5
  },
  {
    "age": 7
  }
]
------------------------

### `parseDouble(string str)`
Parses a string `str` containing a number and returns its decimal value. Trailing zeros are ignored.

*Example*

.Payload
----------
{
    "version":"1.5"
}
----------
.DataSonnet map:
------------------------
ds.parseDouble(payload.version)
------------------------
.Result
------------------------
1.5
------------------------

### `parseHex(string str)`
Parses a hex value given as a string `str` and returns its decimal value.

*Example*

.Payload
----------
{
    "hex":"F"
}
----------
.DataSonnet map:
------------------------
ds.parseHex(payload.hex)
------------------------
.Result
------------------------
15
------------------------

### `parseInt(string str)`
Parses an int value given as a string `str` and returns its integer value.

*Example*

.Payload
----------
{
    "number":"50"
}
----------
.DataSonnet map:
------------------------
ds.parseInt(payload.number)
------------------------
.Result
------------------------
50
------------------------

### `parseOctal(string str)`
Parses an octal value given as a string `str` and returns its integer value.

*Example*

.Payload
----------
{
    "octal":"107136"
}
----------
.DataSonnet map:
------------------------
ds.parseOctal(payload.octal)
------------------------
.Result
------------------------
36446
------------------------

### `prepend(array arr, any val)`
Given `arr` and `val`, inserts `val` at the beginning of `arr`.

*Example*

.Payload
----------
[
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.prepend(payload, 1)
------------------------
.Result
------------------------
[
  1,
  2,
  3,
  4
]
------------------------

### `range(number start, number end)`
Returns an array with the numbers from the `start` to the `end` of the range, inclusive.

*Example*

.Payload
----------
{
    "start": 0,
    "end": 3
}
----------
.DataSonnet map:
------------------------
ds.range(payload.start, payload.end)
------------------------
.Result
------------------------
[
  0,
  1,
  2,
  3
]
------------------------

### `read(string data, string mimeType, object params)`
Reads a string `data` as the given `mimetype`.

*Example*

.DataSonnet map:
------------------------
ds.read("{\"price\": 8.95}", "application/json", {})
------------------------
.Result
------------------------
{
  "price": 8.95
}
------------------------

### `readUrl(string url)`
Reads `url` and returns the content of the url, if it's JSON.

*Example*

.DataSonnet map:
------------------------
ds.readUrl("http://httpbin.org/get")
------------------------
.Result
------------------------
{
  "args": {},
  "headers": {
    "Accept": "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2",
    "Host": "httpbin.org",
    "User-Agent": "Java/14.0.1",
    "X-Amzn-Trace-Id": "Root=1-5f7f568d-481e623471c21cc2686e53e8"
  },
  "origin": "69.250.49.68",
  "url": "http://httpbin.org/get"
}
------------------------

### `remove(array|object item, string|array value)`
Removes `value` from `item` and returns the remaining array or object.
All properties of the object can be removed using a `value` in the array format.

*Example*

.Payload
----------
{
    "array": [
        1,
        2,
        3,
        4
    ],
    "obj": {
        "a": 1,
        "b": 2
    }
}
----------
.DataSonnet map:
------------------------
{
  array: ds.remove(payload.array, 3),
  obj: ds.remove(payload.obj, "b"),
  emptyObj: ds.remove(payload.obj, ["a","b"])
}
------------------------
.Result
------------------------
{
  "array": [
    1,
    2,
    4
  ],
  "obj": {
    "a": 1
  },
  "emptyObj": {}
}
------------------------

### `removeMatch(array|object items, any val)`
Given an array or an object `items` and `val` of the same type, removes the matching values. If `items` is an object, both key and value must match.

*Example*

.Payload
----------
{
    "array": [1,2,3,4],
    "obj": {"a":1,"b":2}
}
----------
.DataSonnet map:
------------------------
{
  array: ds.removeMatch(payload.array, [1,4]),
  obj: ds.removeMatch(payload.obj, {a:1,b:3})
}
------------------------
.Result
------------------------
{
  "array": [
    2,
    3
  ],
  "obj": {
    "b": 2
  }
}
------------------------

### `replace(string phrase, string regex, string replacement)`
Replaces the matching `regex` with the `replacement` in the `phrase`.

*Example*

.Payload
----------
{
    "regex": "Hello",
    "replacement": "Goodbye"
}
----------
.DataSonnet map:
------------------------
ds.replace("Hello World", payload.regex, payload.replacement)
------------------------
.Result
------------------------
"Goodbye World"
------------------------

### `reverse(array|object items)`
Given an array or object as `items`, reverses the order of the elements.

*Example*

.Payload
----------
{
    "array": [
        1,
        2,
        3,
        4
    ],
    "obj": {
        "a":1,
        "b":2
    }
}
----------
.DataSonnet map:
------------------------
{
  array: ds.reverse(payload.array),
  obj: ds.reverse(payload.obj)
}
------------------------
.Result
------------------------
{
  "array": [
    4,
    3,
    2,
    1
  ],
  "obj": {
    "b": 2,
    "a": 1
  }
}
------------------------

### `scan(string str, string regex)`
Executes the regex expression `regex` against `str` and returns an array with each match as an array.

*Example*

.Payload
----------
{
    "email": "test@server.com"
}
----------
.DataSonnet map:
------------------------
ds.scan(payload.email, "(.*)@(.*)(.com)")
------------------------
.Result
------------------------
[
  [
    "test@server.com",
    "test",
    "server",
    ".com"
  ]
]
------------------------

### `select(object obj, string path`
Returns a value inside `obj` by the provided `path`. For nested objects, the path is separated by a dot ('.').

*Example*

.Payload
----------
{
  "language": {
      "name": "Java",
      "version": "1.8"
  }
}
----------
.DataSonnet map:
------------------------
{
  language: ds.select(payload, 'language.name')
}
------------------------
.Result
------------------------
{
  "language": "Java"
}
------------------------

### `sizeOf(any val)`
Returns the size of `val`.

*Example*

.Payload
----------
{
    "array": [1, 2],
    "obj": {"prop": 2},
    "string": "x"
}
----------
.DataSonnet map:
------------------------
{
    array: ds.sizeOf(payload.array),
    object: ds.sizeOf(payload.obj),
    'null': ds.sizeOf(null),
    'function': ds.sizeOf(function(a,b,c) 1),
    string: ds.sizeOf(payload.string)
}
------------------------
.Result
------------------------
{
  "array": 2,
  "object": 1,
  "null": 0,
  "function": 3,
  "string": 1
}
------------------------

### `splitBy(string strToSplit, string regex)`
Splits `strToSplit` into an array based on the matching `regex`.

*Example*

.Payload
----------
{
    "string": "Hello World"
}
----------
.DataSonnet map:
------------------------
ds.splitBy(payload.string, " ")
------------------------
.Result
------------------------
[
  "Hello",
  "World"
]
------------------------

### `startsWith(string str, string subStr)`
Checks if `str` starts with `subStr`. Ignores casing.

*Example*

.Payload
----------
{
    "string": "Hello World"
}
----------
.DataSonnet map:
------------------------
ds.startsWith(payload.string, "hello")
------------------------
.Result
------------------------
true
------------------------

### `toString(any val)`
Returns `val` to a string.

*Example*

.Payload
----------
{
    "num": 5
}
----------
.DataSonnet map:
------------------------
ds.toString(payload.num)
------------------------
.Result
------------------------
"5"
------------------------

### `trim(string str)`
Removes leading and trailing spaces in `str`.

*Example*

.Payload
----------
{
    "string": "      Hello World       "
}
----------
.DataSonnet map:
------------------------
ds.trim(payload.string)
------------------------
.Result
------------------------
"Hello World"
------------------------

### `typeOf(any val)`
Returns a string describing the type of object `val` is.

*Example*

.DataSonnet map:
------------------------
{
    string: ds.typeOf(""),
    bool: ds.typeOf(true),
    "null": ds.typeOf(null),
    number: ds.typeOf(0),
    "function": ds.typeOf(function() 1),
    array: ds.typeOf([]),
    object: ds.typeOf({})
}
------------------------
.Result
------------------------
{
  "string": "string",
  "bool": "boolean",
  "null": "null",
  "number": "number",
  "function": "function",
  "array": "array",
  "object": "object"
}
------------------------

### `unzip(array arr)`
Unzips an array of arrays `arr` and creates a new array of arrays based on their index in `arr`.

*Example*

.Payload
----------
[
  [
    1,
    2
  ],
  [
    1,
    2
  ]
]
----------
.DataSonnet map:
------------------------
ds.unzip(payload)
------------------------
.Result
------------------------
[
  [
    1,
    1
  ],
  [
    2,
    2
  ]
]
------------------------

### `upper(string str)`
Converts a string to all uppercase characters.

*Example*

.Payload
----------
{
    "string": "HeLlO wOrLd"
}
----------
.DataSonnet map:
------------------------
ds.upper(payload.string)
------------------------
.Result
------------------------
"HELLO WORLD"
------------------------

### `uuid`
Generates random alphanumeric uuid.

*Example*

.DataSonnet map:
------------------------
ds.uuid
------------------------
.Result
------------------------
"cj36alpm-8mlt-fm43-8vth-mbd961259lqh"
------------------------

### `valuesOf(object obj)`
Given an object `obj`, returns an array of the values inside `obj`.

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
}
----------
.DataSonnet map:
------------------------
ds.valuesOf(payload)
------------------------
.Result
------------------------
[
  "PHX",
  "SEA"
]
------------------------

### `write(array|object item, string mimeType, object params)`
Converts `item` to a string.

*Example*

.Payload
----------
{
    "price": 8.95
}
----------
.DataSonnet map:
------------------------
ds.write(payload, "application/json", {})
------------------------
.Result
------------------------
"{\"price\":8.95}"
------------------------

### `zip(array array1, array array2)`
Accepts `array1` and `array2` and combines them into one using elements with matching indexes.

*Example*

.Payload
----------
{
    "firstNames": ["Evelyn", "Herman"],
    "lastNames": ["Waugh" , "Melville", "Tolkien"]
}
----------
.DataSonnet map:
------------------------
ds.zip(payload.firstNames, payload.lastNames)
------------------------
.Result
------------------------
[
  [
    "Evelyn",
    "Waugh"
  ],
  [
    "Herman",
    "Melville"
  ]
]
------------------------

## arrays

### `countBy(array arr, function func)`
Returns the number of items in `arr` that passes the condition of `func`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4,
    5
]
----------
.DataSonnet map:
------------------------
ds.arrays.countBy(payload, function(item) item > 2)
------------------------
.Result
------------------------
3
------------------------

### `deepFlatten(array arr)`
Given `arr`, which contains one level and multi level arrays, returns a flat array.

*Example*

.Payload
----------
[
  [
    1,
    2
  ],
  [
    3,
    4,
    [
      5,
      6
    ]
  ]
]
----------
.DataSonnet map:
------------------------
ds.arrays.deepFlatten(payload)
------------------------
.Result
------------------------
[
  1,
  2,
  3,
  4,
  5,
  6
]
------------------------

### `divideBy(array arr, number size)`
Divides a single array `arr` into multiple arrays, limiting each one to `size`.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.divideBy(payload, 2)
------------------------
.Result
------------------------
[
  [
    1,
    2
  ],
  [
    3,
    4
  ],
  [
    5
  ]
]
------------------------

### `drop(array arr, number index)`
Removes every item in `arr` until the specified `index` is reached.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.drop(payload, 3)
------------------------
.Result
------------------------
[
  4,
  5
]
------------------------

### `dropWhile(array arr, function func)`
Removes every item in `arr` until `func` returns a false result, then stops.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.dropWhile(payload, function(item) item < 3)
------------------------
.Result
------------------------
[
  3,
  4,
  5
]
------------------------

### `duplicates(array arr)`
Returns the values that exist more than once in `arr`.

*Example*

.Payload
----------
[
  1,
  1,
  2
]
----------
.DataSonnet map:
------------------------
ds.arrays.duplicates(payload)
------------------------
.Result
------------------------
[
  1
]
------------------------

### `every(array arr, function func)`
Returns true if every value `arr` returns true in `func`.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.every(payload, function(item) item > 0)
------------------------
.Result
------------------------
true
------------------------

### `firstWith(array arr, function func)`
Returns the first value that passes the condition of `func` then stops.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.firstWith(payload, function(item,index) item == index + 1)
------------------------
.Result
------------------------
1
------------------------

### `indexOf(array arr, any value)`
Returns the current index of the matching `value` in `arr`.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.indexOf(payload, 3)
------------------------
.Result
------------------------
2
------------------------

### `indexWhere(array arr, function func)`
Returns the first index where the condition of `func` passes.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.indexWhere(payload, function(item) item == 3)
------------------------
.Result
------------------------
2
------------------------

### `join(array arrL, array arrR, function funcL, function funcR)`
Joins two arrays together, returns the items of `arrL` with the items that match from `arrR`.

Both functions `funcL` and `funcR` are expected to take the item as the first parameter (required).

*Example*

.Payload
----------
{
    "countries": [
      {
        "id": 1,
        "name":"Spain"
      },
      {
        "id": 2,
        "name":"France"
      },
      {
        "id": 3,
        "name":"Germany"
      }
    ],
    "languages": [
      {
        "countryId": 1,
        "name":"Spanish"
      },
      {
        "countryId": 2,
        "name":"French"
      },
      {
        "countryId": 4,
        "name":"Danish"
      }
    ]
}
----------
.DataSonnet map:
------------------------
ds.arrays.join(
    payload.countries,
    payload.languages,
    function(item) item.id,
    function(item) item.countryId
)
------------------------
.Result
------------------------
[
  {
    "r": {
      "countryId": 1,
      "name": "Spanish"
    },
    "l": {
      "id": 1,
      "name": "Spain"
    }
  },
  {
    "r": {
      "countryId": 2,
      "name": "French"
    },
    "l": {
      "id": 2,
      "name": "France"
    }
  }
]
------------------------

### `leftJoin(array arrL, array arrR, function funcL, function funcR)`
Joins two arrays together, returns all of the items of `arrL`, with the items that match from `arrR`.

Both functions `funcL` and `funcR` are expected to take the item as the first parameter (required).

*Example*

.Payload
----------
{
    "countries": [
      {
        "id": 1,
        "name":"Spain"
      },
      {
        "id": 2,
        "name":"France"
      },
      {
        "id": 3,
        "name":"Germany"
      }
    ],
    "languages": [
      {
        "countryId": 1,
        "name":"Spanish"
      },
      {
        "countryId": 2,
        "name":"French"
      },
      {
        "countryId": 4,
        "name":"Danish"
      }
    ]
}
----------
.DataSonnet map:
------------------------
ds.arrays.leftJoin(
    payload.countries,
    payload.languages,
    function(item) item.id,
    function(item) item.countryId
)
------------------------
.Result
------------------------
[
  {
    "r": {
      "countryId": 1,
      "name": "Spanish"
    },
    "l": {
      "id": 1,
      "name": "Spain"
    }
  },
  {
    "r": {
      "countryId": 2,
      "name": "French"
    },
    "l": {
      "id": 2,
      "name": "France"
    }
  },
  {
    "l": {
      "id": 3,
      "name": "Germany"
    }
  }
]
------------------------

### `outerJoin(array arrL, array arrR, function funcL, function funcR)`
Joins two arrays together, returns the items of `arrL` with the items that match from `arrR`, the items from `arrL` that don't have matches, and items from `arrR` that don't have matches.

Both functions `funcL` and `funcR` are expected to take the item as the first parameter (required).

*Example*

.Payload
----------
{
    "countries": [
      {
        "id": 1,
        "name":"Spain"
      },
      {
        "id": 2,
        "name":"France"
      },
      {
        "id": 3,
        "name":"Germany"
      }
    ],
    "languages": [
      {
        "countryId": 1,
        "name":"Spanish"
      },
      {
        "countryId": 2,
        "name":"French"
      },
      {
        "countryId": 4,
        "name":"Danish"
      }
    ]
}
----------
.DataSonnet map:
------------------------
ds.arrays.outerJoin(
    payload.countries,
    payload.languages,
    function(item) item.id,
    function(item) item.countryId
)
------------------------
.Result
------------------------
[
  {
    "r": {
      "countryId": 1,
      "name": "Spanish"
    },
    "l": {
      "id": 1,
      "name": "Spain"
    }
  },
  {
    "r": {
      "countryId": 2,
      "name": "French"
    },
    "l": {
      "id": 2,
      "name": "France"
    }
  },
  {
    "l": {
      "id": 3,
      "name": "Germany"
    }
  },
  {
    "r": {
      "countryId": 4,
      "name": "Danish"
    }
  }
]
------------------------

### `occurrences(array arr, function func)`
Returns an object where the keys of the object are the result of `func` and the values of the object indicate how many times the key occurs in `arr`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
  "a",
  "a",
  "b",
  "b",
  "b",
  "c"
]
----------
.DataSonnet map:
------------------------
ds.arrays.occurrences(payload, function(item) item)
------------------------
.Result
------------------------
{
  "a": 2,
  "b": 3,
  "c": 1
}
------------------------

### `partition(array arr, function func)`
Splits `arr` into two arrays of successes and failures from the results of `func`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.partition(payload, function(item) item > 3)
------------------------
.Result
------------------------
{
  "success": [
    4,
    5
  ],
  "failure": [
    1,
    2,
    3
  ]
}
------------------------

### `slice(array arr, number start, number end)`
Returns a subset of `arr` between the indexes of `start` and `end`.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.slice(payload, 2, 4)
------------------------
.Result
------------------------
[
  3,
  4
]
------------------------

### `some(array arr, function func)`
Returns true if at least one item in `arr` passes the condition in `func`.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.some(payload, function(item) item > 2)
------------------------
.Result
------------------------
true
------------------------

### `splitAt(array arr, number index)`
Splits `arr` into a left and right array based on the `index`.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.splitAt(payload, 3)
------------------------
.Result
------------------------
{
  "r": [
    4,
    5
  ],
  "l": [
    1,
    2,
    3
  ]
}
------------------------

### `splitWhere(array arr, function func)`
Splits `arr` into a left and right array based on the first index that returns true for `func`.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.splitWhere(payload, function(item) item > 3)
------------------------
.Result
------------------------
{
  "r": [
    4,
    5
  ],
  "l": [
    1,
    2,
    3
  ]
}
------------------------

### `sumBy(array arr, function func)`
Calculates the sum of `arr` by the function provided value.

The function `func` is expected to take the item as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.sumBy(payload, function(item) item)
------------------------
.Result
------------------------
15
------------------------

### `take(array arr, number index)`
Returns all values from `arr` up to the `index`.

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4
]
----------
.DataSonnet map:
------------------------
ds.arrays.take(payload, 3)
------------------------
.Result
------------------------
[
  1,
  2,
  3
]
------------------------

### `takeWhile(array arr, function func)`
Takes all items from the array while `func` is true. Stops at the first false value.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
  1,
  2,
  3,
  4,
  5
]
----------
.DataSonnet map:
------------------------
ds.arrays.takeWhile(payload, function(item) item < 3)
------------------------
.Result
------------------------
[
  1,
  2
]
------------------------

## binaries

### `fromBase64(string value)`
Converts `value` from base64.

*Example*

.DataSonnet map:
------------------------
ds.binaries.fromBase64("SGVsbG8gV29ybGQ=")
------------------------
.Result
------------------------
"Hello World"
------------------------

### `fromHex(string value)`
Converts `value` from hexadecimal.

*Example*

.DataSonnet map:
------------------------
ds.binaries.fromHex("48656C6C6F20576F726C64")
------------------------
.Result
------------------------
"Hello World"
------------------------

### `readLinesWith(string value, string encoding)`
Reads `value` with the specified encoding `encoding`.

*Example*

.DataSonnet map:
------------------------
ds.binaries.readLinesWith("Hello World", "UTF-8")
------------------------
.Result
------------------------
["Hello World"]
------------------------

### `toBase64(any value)`
Converts `value` to base 64.

*Example*

.DataSonnet map:
------------------------
ds.binaries.toBase64("Hello World")
------------------------
.Result
------------------------
"SGVsbG8gV29ybGQ="
------------------------

### `toHex(any value)`
Converts `value` to hexadecimal.

*Example*

.DataSonnet map:
------------------------
ds.binaries.toHex("Hello World")
------------------------
.Result
------------------------
"48656C6C6F20576F726C64"
------------------------

### `writeLinesWith(string value, string encoding)`
Writes `value` with the specified encoding `encoding`.

*Example*

.DataSonnet map:
------------------------
ds.binaries.writeLinesWith(["Hello World"], "UTF-8")
------------------------
.Result
------------------------
"Hello World\n"
------------------------

## crypto

### `hash(string value, string algorithm)`
Calculates hash of `value` using one of the supported algorithms. The `algorithm` must be one of `MD2`, `MD5`, `SHA-1`, `SHA-256`, `SHA-384`, `SHA-512`
The response is a string containing the hash bytes.

*Example:*

------------------------
{
    hashValue: ds.crypto.hash("HelloWorld", "MD5")
}
------------------------
.Result
------------------------
{
    "hashValue": "68e109f0f40ca72a15e05cc22786f8e6"
}
------------------------
### `hmac(string value, string secret, string algorithm)`
Generates hash-based message authentication code using provided `value`, `secret`, and a hash function `algorithm`. The `algorithm` must be one of `HmacSHA1`, `HmacSHA256` or `HmacSHA512`.

*Example:*

------------------------
{
    hmacValue: ds.crypto.hmac("HelloWorld", "DataSonnet rules!", "HmacSHA256")
}
------------------------
.Result
------------------------
{
    "hmacValue": "7854220ef827b07529509f68f391a80bf87fff328dbda140ed582520a1372dc1"
}
------------------------

## datetime

### `now()`
Returns the current date/time from the system UTC clock in ISO-8601 format.

*Example*

------------------------
{
    currentZuluTime: ds.datetime.now()
}
------------------------

.Result:
------------------------
{
    "currentZuluTime": "2019-08-19T18:58:38.313Z"
}
------------------------

### `daysBetween(string datetime1, string datetime2)`
Returns the number of days between `datetime1` and `datetime2`. Dates are in "yyyy-MM-dd'T'HH:mm:ss.SSSVV" format.

*Example*

.DataSonnet map:
------------------------
local date1 = "2019-09-20T18:53:41.425Z";
local date2 = "2019-09-14T18:53:41.425Z";

ds.datetime.daysBetween(date1, date2)
------------------------
.Result
------------------------
6
------------------------

### `format(string datetime, string inputFormat, string outputFormat)`
Reformats `datetime` using `inputFormat` and `outputFormat`.

*Example*

------------------------
ds.datetime.format("2019-07-04T21:00:00Z", "yyyy-MM-dd'T'HH:mm:ssVV", "d MMM uuuu")
------------------------
.Result:
------------------------
4 Jul 2019
------------------------

### `isLeapYear(string datetime)`
Returns a boolean indicating if `datetime` is a leap year. Dates are in "yyyy-MM-dd'T'HH:mm:ss.SSSVV" format.

*Example*

.DataSonnet map:
------------------------
ds.datetime.isLeapYear("2019-09-14T18:53:41.425Z")
------------------------
.Result
------------------------
false
------------------------

### `compare(string datetime1, string format1, string datetime2, string format2)`
Returns `1` if `datetime1 > datetime2`, `-1` if `datetime1 < datetime2`, and `0` if `datetime1 == datetime2`.

*Example*

------------------------
ds.datetime.compare("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ", "2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result
------------------------
0
------------------------

### `changeTimeZone(string datetime, string format, string timezone)`
Changes the date timezone, retaining the instant. This normally results in a change to the local date-time.
The response is formatted using the same format as an input.

*Example*

------------------------
ds.datetime.changeTimeZone("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ", "America/Los_Angeles")
------------------------
.Result:
------------------------
2019-07-04T19:00:00-0700
------------------------

### `toLocalDate(string datetime, string format)`
Returns only local date part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalDate("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
2019-07-04
------------------------

### `toLocalTime(string datetime, string format)`
Returns only local time part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalTime("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
21:00:00
------------------------

### `toLocalDateTime(string datetime, string format)`
Returns local datetime part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalDateTime("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
2019-07-04T21:00:00
------------------------

### `offset(string datetime, string period)`
Returns the local datetime part of the `datetime` parameter in the ISO-8601 format without the offset.
The `period` is a string in the ISO-8601 period format.

*Example*

------------------------
ds.datetime.offset("2019-07-22T21:00:00Z", "P1Y1D")
------------------------
.Result:
------------------------
2020-07-23T21:00:00Z
------------------------

## localdatetime

### `now()`
Returns the current date/time from the system UTC clock in ISO-8601 format without a time zone.

*Example*

------------------------
{
    currentLocalTime: ds.localdatetime.now()
}
------------------------

.Result:
------------------------
{
    "currentLocalTime": "2019-08-19T18:58:38.313"
}
------------------------

### `offset(string datetime, string period)`
Returns a copy of `datetime` with the specified amount added. The `datetime` parameter is in the ISO-8601 format without an offset.
The `period` is a string in the ISO-8601 period format.

*Example*

------------------------
ds.localdatetime.offset("2019-07-22T21:00:00", "P1Y1D")
------------------------
.Result:
------------------------
2020-07-23T21:00:00
------------------------

### `format(string datetime, string inputFormat, string outputFormat)`
Reformats a local date-time string.

*Example*

------------------------
ds.localdatetime.format("2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss", "d MMM uuuu")
------------------------
.Result:
------------------------
4 Jul 2019
------------------------

### `compare(string datetime1, string format1, string datetime2, string format2)`
Returns `1` if `datetime1 > datetime2`, `-1` if `datetime1 < datetime2`, and `0` if `datetime1 == datetime2`.
The `format1` and `format2` parameters must not have an offset or time zone.

*Example*

------------------------
ds.localdatetime.compare("2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss", "2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss")
------------------------
.Result:
------------------------
0
------------------------

## jsonpath

### `select(object json, string path)`

Evaluates JsonPath expression and returns the resulting JSON object.
It uses the https://github.com/json-path/JsonPath[Jayway JsonPath implementation] and fully supports https://goessner.net/articles/JsonPath/[JsonPath specification].

*Example*

.Payload
------------------------
{
  "store": {
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ]
  }
}
------------------------
.DataSonnet map:
------------------------
{
    author: ds.jsonpath.select(payload, "$..book[-2:]..author")[0]
}
------------------------
.Result
------------------------
{
    "author": "Herman Melville"
}
------------------------

## math

### `abs(number num)`
Returns the absolute value of `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.abs(-1)
------------------------
.Result
------------------------
1
------------------------

### `acos(number num)`
Performs math acos operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.acos(1)
------------------------
.Result
------------------------
0
------------------------

### `asin(number num)`
Performs math asin operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.asin(1)
------------------------
.Result
------------------------
1.5707963267948966
------------------------

### `atan(number num)`
Performs math atan operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.atan(1)
------------------------
.Result
------------------------
0.7853981633974483
------------------------

### `avg(array arr)`
Returns the average value of `arr`.

*Example*

.DataSonnet map:
------------------------
ds.math.avg([1,2,3])
------------------------
.Result
------------------------
2
------------------------

### `ceil(number num)`
Rounds `num` up.

*Example*

.DataSonnet map:
------------------------
ds.math.ceil(1.01)
------------------------
.Result
------------------------
2
------------------------

### `clamp(number value, number minVal, number maxVal)`
Limits `value` to the range of `minVal` and `maxVal`.

*Example*

.DataSonnet map:
------------------------
ds.math.clamp(100, 0, 10)
------------------------
.Result
------------------------
10
------------------------

### `cos(number num)`
Performs math cos operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.cos(0)
------------------------
.Result
------------------------
1
------------------------

### `exp(number num)`
Returns the result of e to the power of `num`, in other words e^`num`^.

*Example*

.DataSonnet map:
------------------------
ds.math.exp(2)
------------------------
.Result
------------------------
7.38905609893065
------------------------

### `exponent(number num)`
Returns the non-decimal portion of a logarithmic operation.

exponent = (log(`num`)/log(2)) + 1

*Example*

.DataSonnet map:
------------------------
ds.math.exponent(2)
------------------------
.Result
------------------------
2
------------------------

### `floor(number num)`
Rounds `num` down.

*Example*

.DataSonnet map:
------------------------
ds.math.floor(4.99)
------------------------
.Result
------------------------
4
------------------------

### `log(number num)`
Performs math log operation. on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.log(2)
------------------------
.Result
------------------------
0.6931471805599453

------------------------

### `mantissa(number num)`
Returns the decimal portion of a logarithmic operation.

exponent = (log(`num`)/log(2)) + 1
mantissa = `num` * pow(2, -exponent)

*Example*

.DataSonnet map:
------------------------
ds.math.mantissa(2)
------------------------
.Result
------------------------
0.5
------------------------

### `mod(number num1, number num2)`
Performs modulo operation, returns how many times `num1` can go into `num2`.

*Example*

.DataSonnet map:
------------------------
ds.math.mod(2,4)
------------------------
.Result
------------------------
2
------------------------

### `pow(number num1, number num2)`
Returns the value of `num1` to the power of `num2`, in other words `num1`^`num2`^.

*Example*

.DataSonnet map:
------------------------
ds.math.pow(2,2)
------------------------
.Result
------------------------
4
------------------------

### `random`
Returns a random float value between 0 and 1.

*Example*

.DataSonnet map:
------------------------
ds.math.random
------------------------
.Result
------------------------
0.5963038027787421
------------------------

### `randomInt(number num)`
Returns a random integer between 0 and the provided number inclusive.

*Example*

.DataSonnet map:
------------------------
ds.math.randomInt(500)
------------------------
.Result
------------------------
485
------------------------

### `round(number num)`
Rounds `num` to the nearest whole number.

*Example*

.DataSonnet map:
------------------------
ds.math.round(2.5)
------------------------
.Result
------------------------
3
------------------------

### `sin(number num)`
Performs math sin operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.sin(1)
------------------------
.Result
------------------------
0.8414709848078965
------------------------

### `sqrt(number num)`
Performs math square root operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.sqrt(4)
------------------------
.Result
------------------------
2
------------------------

### `sum(array arr)`
Returns sum of all elements in `arr`.

*Example*

.Payload
----------
[ 10, 20, 30 ]
----------
.DataSonnet map:
------------------------
ds.math.sum(payload)
------------------------
.Result
------------------------
60
------------------------

### `tan(number num)`
Performs math tan operation on `num`.

*Example*

.DataSonnet map:
------------------------
ds.math.tan(1)
------------------------
.Result
------------------------
1.5574077246549023
------------------------

## numbers

### `fromBinary(number value)`
Converts `value` from binary to decimal.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromBinary(1100100)
------------------------
.Result
------------------------
100
------------------------

### `fromHex(number value)`
Converts `value` from hex to decimal.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromHex(64)
------------------------
.Result
------------------------
100
------------------------

### `fromRadixNumber(number value, number baseAsBinary)`
Converts `value` to a decimal with the base `baseAsBinary`.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromRadixNumber(1101000, 2)
------------------------
.Result
------------------------
104
------------------------

### `toBinary(number value)`
Converts `value` from decimal to binary.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toBinary(100)
------------------------
.Result
------------------------
"1100100"
------------------------

### `toHex(number value)`
Converts `value` from decimal to hex.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toHex(100)
------------------------
.Result
------------------------
"64"
------------------------

### `toRadixNumber(number value, number baseAsDecimal)`
Converts `value` to a number with the base `baseAsDecimal`.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toRadixNumber(104, 2)
------------------------
.Result
------------------------
"1101000"
------------------------

## objects

### `divideBy(object obj, number num)`
Creates an array of objects where each nested object has the specified number `num` of key-value pairs.

*Example*

.Payload
----------
{
  "a":1,
  "b":2,
  "c":3
}
----------
.DataSonnet map:
------------------------
ds.objects.divideBy(payload, 2)
------------------------
.Result
------------------------
[
  {
    "a": 1,
    "b": 2
  },
  {
    "c": 3
  }
]
------------------------

### `everyEntry(object obj, function func)`
Returns a boolean depending on if all key-value pairs of `obj` pass the `func`.

The function `func` is expected to take the value as the first parameter (required) and the key as the second parameter (optional).

*Example*

.Payload
----------
{
  "a":1,
  "b":2,
  "c":1
}
----------
.DataSonnet map:
------------------------
ds.objects.everyEntry(payload,function(value,key) value < 2)
------------------------
.Result
------------------------
false
------------------------

### `mergeWith(object obj1, object obj2)`
Combines `obj1` and `obj2`.

*Example*

.Payload
----------
{
  "obj1": {
    "a":1
  },
  "obj2":{
    "b":2
  }
}
----------
.DataSonnet map:
------------------------
ds.objects.mergeWith(payload.obj1,payload.obj2)
------------------------
.Result
------------------------
{
  "a": 1,
  "b": 2
}
------------------------

### `someEntry(object obj, function func)`
Returns a boolean depending on if at least one key-value pair passes the function `func`.

The function `func` is expected to take the property value as the first parameter (required) and  the property key as the second (required).

*Example*

.Payload
----------
{
  "a":1,
  "b":2,
  "c":1
}
----------
.DataSonnet map:
------------------------
ds.objects.someEntry(payload, function(value, key) value < 2)
------------------------
.Result
------------------------
true
------------------------

### `takeWhile(object obj, function func)`
Takes all key value pairs that result in true from the function. Stops on the first value that fails.

The function `func` is expected to take the property value as the first parameter (required) and  the property key as the second (required).

*Example*

.Payload
----------
{
  "a":1,
  "b":2,
  "c":1
}
----------
.DataSonnet map:
------------------------
ds.objects.takeWhile(payload, function(value,key) value < 2)
------------------------
.Result
------------------------
{
  "a": 1
}
------------------------

## regex

### `regexFullMatch(string pattern, string input)`
Matches the entire input against the pattern (anchored start and end). If there's no match, returns `null`. If there's a match, returns a JSON object which has the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexFullMatch(@'h(?P<mid>.*)o', 'hello')
------------------------
.Result
------------------------
{
  "string": "hello",
  "captures": [
    "ell"
  ],
  "namedCaptures": {
    "mid": "ell"
  }
}
------------------------

### `regexPartialMatch(string pattern, string input)`
Matches the input against the pattern (unanchored). If there's no match, returns `null`. If there's a match, returns a JSON object which has the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexPartialMatch(@'e(?P<mid>.*)o', 'hello')
------------------------
.Result
------------------------
{
  "string": "ello",
  "captures": [
    "ll"
  ],
  "namedCaptures": {
    "mid": "ll"
  }
}
------------------------

### `regexScan(string pattern, string input)`
Finds all matches of the input against the pattern. If there are any matches, returns an array of JSON objects which have the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexScan(@'(?P<user>[a-z]*)@(?P<domain>[a-z]*).org', 'modus@datasonnet.org,box@datasonnet.org')
------------------------
.Result
------------------------
[
  {
    "string": "modus@datasonnet.org",
    "captures": [
      "modus",
      "datasonnet"
    ],
    "namedCaptures": {
      "domain": "datasonnet",
      "user": "modus"
    }
  },
  {
    "string": "box@datasonnet.org",
    "captures": [
      "box",
      "datasonnet"
    ],
    "namedCaptures": {
      "domain": "datasonnet",
      "user": "box"
    }
  }
]
------------------------

### `regexQuoteMeta(string str)`
Returns a literal pattern string for the specified string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexQuoteMeta(@'1.5-2.0?')
------------------------
.Result
------------------------
"1\\.5-2\\.0\\?"
------------------------

### `regexReplace(string str, string pattern, string replacement)`
Returns the input with the first match replaced by `replacement` string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexReplace('wishyfishyisishy', @'ish', 'and')
------------------------
.Result
------------------------
"wandyfishyisishy"
------------------------

### `regexGlobalReplace(string str, string pattern, string replacement)`
Returns the input with all matches replaced by `replacement` string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexGlobalReplace('wishyfishyisishy', @'ish', 'and')
------------------------
.Result
------------------------
"wandyfandyisandy"
------------------------

## strings

### `appendIfMissing(string str, string value)`
Appends `str` with `value` if `str` does not already end with `value`.

*Example*

.DataSonnet map:
------------------------
{
    existing: ds.strings.appendIfMissing("Hello World","World"),
    missing: ds.strings.appendIfMissing("Hello ","World")
}
------------------------
.Result
------------------------
{
  "existing": "Hello World",
  "missing": "Hello World"
}
------------------------

### `camelize(string str)`
Converts words in `str` using camel case, which removes all spaces and converts the first letter of each word except the first word to upper case.

*Example*

.DataSonnet map:
------------------------
ds.strings.camelize("Hello_world")
------------------------
.Result
------------------------
"helloWorld"
------------------------

### `capitalize(string str)`
Converts words in `str` using capitalized case, which changes the first letter of each word to uppercase, with the rest of the letters in lowercase.

*Example*

.DataSonnet map:
------------------------
ds.strings.capitalize("hello world")
------------------------
.Result
------------------------
"Hello World"
------------------------

### `charCode(string char)`
Converts `char` to its char code.

*Example*

.DataSonnet map:
------------------------
ds.strings.charCode("*")
------------------------
.Result
------------------------
42
------------------------

### `charCodeAt(string str, number index)`
Returns the char code at `index` in `str`.

*Example*

.DataSonnet map:
------------------------
ds.strings.charCodeAt("*", 0)
------------------------
.Result
------------------------
42
------------------------

### `dasherize(string str)`
Converts words in `str` using kebab-case, which converts all letters in `str` to lowercase and all spaces into dashes (-).

*Example*

.DataSonnet map:
------------------------
ds.strings.dasherize("Hello WorldX")
------------------------
.Result
------------------------
"hello-world-x"
------------------------

### `fromCharCode(number charCode)`
Converts `charCode` to its string value.

*Example*

.DataSonnet map:
------------------------
ds.strings.fromCharCode(42)
------------------------
.Result
------------------------
"*"
------------------------

### `isAlpha(string str)`
Returns a boolean which determines if the provided string only contains alpha characters.

*Example*

.DataSonnet map:
------------------------
ds.strings.isAlpha("abcde")
------------------------
.Result
------------------------
true
------------------------

### `isAlphanumeric(string str)`
Returns a boolean which determines if `str` only contains alpha numeric values.

*Example*

.DataSonnet map:
------------------------
ds.strings.isAlphanumeric("a1b2cd3e4")
------------------------
.Result
------------------------
true
------------------------

### `isLowerCase(string str)`
Returns a boolean which determines if `str` is all lowercase.

*Example*

.DataSonnet map:
------------------------
ds.strings.isLowerCase("hello")
------------------------
.Result
------------------------
true
------------------------

### `isNumeric(string str)`
Returns a boolean which determines if `str` contains only numbers.

*Example*

.DataSonnet map:
------------------------
ds.strings.isNumeric("34634")
------------------------
.Result
------------------------
true
------------------------

### `isUpperCase(string str)`
Returns a boolean which determines if `str` is all uppercase.

*Example*

.DataSonnet map:
------------------------
ds.strings.isUpperCase("HELLO")
------------------------
.Result
------------------------
true
------------------------

### `isWhitespace(string str)`
Returns a boolean which determines if `str` only contains spaces.

*Example*

.DataSonnet map:
------------------------
ds.strings.isWhitespace("      ")
------------------------
.Result
------------------------
true
------------------------

### `leftPad(string str, number offset)`
Pads the left side of `str` with spaces if the string is below the `offset` length.

*Example*

.DataSonnet map:
------------------------
ds.strings.leftPad("Hello",10)
------------------------
.Result
------------------------
"     Hello"
------------------------

### `ordinalize(number num)`
Converts `num` to its ordinal string format, e.g. 1st, 2nd, 3rd, etc.

*Example*

.DataSonnet map:
------------------------
ds.strings.ordinalize(1)
------------------------
.Result
------------------------
"1st"
------------------------

### `pluralize(string singularWord)`
Converts `singularWord` to its plural counterpart. May not work with all edge cases.

*Example*

.DataSonnet map:
------------------------
ds.strings.pluralize("car")
------------------------
.Result
------------------------
"cars"
------------------------

### `prependIfMissing(string str, string value)`
Prepends `str` with `value` if `str` does not already begin with `value`.

*Example*

.DataSonnet map:
------------------------
{
    existing: ds.strings.prependIfMissing("Hello World","Hello"),
    missing: ds.strings.prependIfMissing(" World","Hello")
}
------------------------
.Result
------------------------
{
  "existing": "Hello World",
  "missing": "Hello World"
}
------------------------

### `repeat(string str, number times)`
Repeats `str` the given amount of `times`.

*Example*

.DataSonnet map:
------------------------
ds.strings.repeat("Hello ", 2)
------------------------
.Result
------------------------
"Hello Hello "
------------------------

### `rightPad(string str, number offset)`
Pads the right side `str` with spaces if the string is below the `offset` length.

*Example*

.DataSonnet map:
------------------------
ds.strings.rightPad("Hello",10)
------------------------
.Result
------------------------
"Hello     "
------------------------

### `singularize(string pluralWord)`
Converts `pluralWord` to a singular word. May not work with all edge cases.

*Example*

.DataSonnet map:
------------------------
ds.strings.singularize("cars")
------------------------
.Result
------------------------
"car"
------------------------

### `substringAfter(string str, string separator)`
Gets the substring of `str` after the first occurrence of the `separator`.

*Example*

.DataSonnet map:
------------------------
ds.strings.substringAfter("!XHelloXWorldXAfter", "X")
------------------------
.Result
------------------------
"HelloXWorldXAfter"
------------------------

### `substringAfterLast(string str, string separator)`
Gets the substring in `str` after the final occurrence of the `separator`.

*Example*

.DataSonnet map:
------------------------
ds.strings.substringAfterLast("!XHelloXWorldXAfter", "X")
------------------------
.Result
------------------------
"After"
------------------------

### `substringBefore(string str, string separator)`
Gets the substring in `str` before the first occurrence of the `separator`.

*Example*

.DataSonnet map:
------------------------
ds.strings.substringBefore("!XHelloXWorldXAfter", "X")
------------------------
.Result
------------------------
"!"
------------------------

### `substringBeforeLast(string str, string separator)`
Gets the substring in `str` before the final occurrence of the `separator`.

*Example*

.DataSonnet map:
------------------------
ds.strings.substringBeforeLast("!XHelloXWorldXAfter", "X")
------------------------
.Result
------------------------
"!XHelloXWorld"
------------------------

### `underscore(string str)`
Converts words in `str` using snake case, which converts all letters in `str` to lowercase and all spaces into underscores (_).

*Example*

.DataSonnet map:
------------------------
ds.strings.underscore("Hello WorldX")
------------------------
.Result
------------------------
"hello_world_x"
------------------------

### `unwrap(string str, string wrapper)`
Returns the `str` without the `wrapper` text.
Returns the `str` without the `wrapper` text.
The `wrapper` text is the prepended and/or appended values to the `str`.


*Example*

.DataSonnet map:
------------------------
{
    exists: ds.strings.unwrap("Hello World Hello","Hello"),
    partial: ds.strings.unwrap("Hello World ","Hello"),
    missing: ds.strings.unwrap(" World ","Hello")
}
------------------------
.Result
------------------------
{
  "exists": " World ",
  "partial": " World Hello",
  "missing": " World "
}
------------------------

### `withMaxSize(string str, number size)`
Limits the `size` of `str`.

*Example*

.DataSonnet map:
------------------------
ds.strings.withMaxSize("Hello World", 5)
------------------------
.Result
------------------------
"Hello"
------------------------

### `wrapIfMissing(string str, string wrapper)`
Prepends and appends the `wrapper` to `str` if `str` is not already wrapped. Will update only missing side if `wrapper` already exists at the beginning or end.

*Example*

.DataSonnet map:
------------------------
{
    exists: ds.strings.wrapIfMissing("Hello World Hello","Hello"),
    partialBeg: ds.strings.wrapIfMissing("Hello World ","Hello"),
    partialEnd: ds.strings.wrapIfMissing(" World Hello","Hello"),
    missing: ds.strings.wrapIfMissing(" World ","Hello")
}
------------------------
.Result
------------------------
{
  "exists": "Hello World Hello",
  "partialBeg": "Hello World Hello",
  "partialEnd": "Hello World Hello",
  "missing": "Hello World Hello"
}
------------------------

### `wrapWith(string str, string wrapper)`
Prepends and appends the `wrapper` to `str`.

*Example*

.DataSonnet map:
------------------------
ds.strings.wrapWith(" World ","Hello")
------------------------
.Result
------------------------
"Hello World Hello"
------------------------

## url

### `decode(string data, string encoding="UTF-8")`

Decodes a application/x-www-form-urlencoded string using a specific encoding scheme. The supplied encoding is used to determine what characters are represented by any consecutive sequences of the form "%xy".

*Example*

.DataSonnet map:
------------------------
ds.url.decode('Hello+World')
------------------------
.Result
------------------------
"Hello World"
------------------------

### `encode(string data, string encoding="UTF-8")`

Translates a string into `application/x-www-form-urlencoded` format using the supplied encoding scheme to obtain the bytes for unsafe characters. The default encoding is `UTF-8`.

*Example*

.DataSonnet map:
------------------------
ds.url.encode('Hello World')
------------------------
.Result
------------------------
"Hello+World"
------------------------
