# DataSonnet Libraries
:toc:
:toclevels: 1

## core

### `append(array arr, any val)`
Given `arr` and `val`, appends `val` to the end of `arr`.

*Example*

.Payload
----------
[
    2,
    3,
    5,
    7
]
----------
.DataSonnet map:
------------------------
ds.append(payload, 11)
------------------------
.Result
------------------------
[
  2,
  3,
  5,
  7,
  11
]
------------------------

### `combine(any first, any second)`
Combines `first` and `second`. Some values will auto-coerce, e.g. the number 5 will auto coerce to the string "5."

*Example*

.Payload
----------
[
    {
        "name": "Java"
    },
    {
        "version": "1.8"
    }
]
----------
.DataSonnet map:
------------------------
{
    "language": ds.combine(payload[0], payload[1])
}
------------------------
.Result
------------------------
{
  "language": {
    "name": "Java",
    "version": "1.8"
  }
}
------------------------

### `contains(array|string item, any val)`
If `item` is an array, returns true if `item` contains `val`.

If `item` is a string, returns true if `item` contains the sub string `val`.

*Example*

.Payload
----------
[
    2,
    3,
    5,
    7
]
----------
.DataSonnet map:
------------------------
ds.contains(payload, 2)
------------------------
.Result
------------------------
true
------------------------

### `distinctBy(array|object item, function discriminator)`
Returns a new object containing only the items that are a unique result from `discriminator`.

The function `discriminator` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
    1,
    1,
    2,
    2,
    3,
    3,
    4,
    4,
    5
]
----------
.DataSonnet map:
------------------------
ds.distinctBy(payload, function(value, index) value)
------------------------
.Result
------------------------
[
  1,
  2,
  3,
  4,
  5
]
------------------------

### `endsWith(string str, string subStr)`
Returns true if `str` ends with `subStr`. Ignores casing.

*Example*

.Payload
----------
{
    "name": "Scala",
    "version": "1.0"
}
----------
.DataSonnet map:
------------------------
ds.endsWith(payload.version, ".0")
------------------------
.Result
------------------------
true
------------------------

### `entriesOf(object obj)`
Returns an array of objects describing each key value pair of `obj`.

*Example*

.Payload
----------
{
    "name": "Scala",
    "version": "1.0"
}
----------
.DataSonnet map:
------------------------
ds.entriesOf(payload)
------------------------
.Result
------------------------
[
  {
    "value": "Scala",
    "key": "name"
  },
  {
    "value": "1.0",
    "key": "version"
  }
]
------------------------

### `filter(array arr, function func)`
Filters `arr` depending on the result of `func`.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.filter(payload, function(value, index) value < 3)
------------------------
.Result
------------------------
[
  1,
  2
]
------------------------

### `filterObject(object obj, function func)`
Filters `obj` depending on the result of `func`.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
    "version": 1.7
}
----------
.DataSonnet map:
------------------------
ds.filterObject(payload, function(value, key, index) value > 1.5)
------------------------
.Result
------------------------
{
  "version": 1.7
}
------------------------

### `find(string|array item, any val)`
Returns an array containing the location where `val` occurs in `item`.

*Example*

.Payload
----------
[
    2,
    3,
    5,
    7
]
----------
.DataSonnet map:
------------------------
ds.find(payload, 2)
------------------------
.Result
------------------------
[
  0
]
------------------------

### `flatMap(array arr, function func)`
Given an array of arrays `arr`, creates a flat array using the outcome of `func`.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
[
    [
        2,
        3,
        5,
        7
    ],
    [
        11,
        13,
        17,
        19
    ]
]
----------
.DataSonnet map:
------------------------
ds.flatMap(payload, function(value, index) value)
------------------------
.Result
------------------------
[
  2,
  3,
  5,
  7,
  11,
  13,
  17,
  19
]
------------------------

### `foldLeft(array arr, function func, any initVal)`
Iterates over `arr`, applying `func` to the previous result. Starts with the value provided in `initVal`.

The function `func` is expected to take the current value as the first parameter (required) and the previous value as the second parameter (required).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.foldLeft(payload, function(curr, prev) curr * prev, 1)
------------------------
.Result
------------------------
24
/*
  1 * 1 = 1
  2 * 1 = 2
  3 * 2 = 6
  4 * 6 = 24
*/
------------------------

### `foldRight(array arr, function func, any initVal)`
Iterates backwards over an array, applying `func` to the previous result. Starts with the value provided in `initVal`.

The function `func` is expected to take the current value as the first parameter (required) and the previous value as the second parameter (required).

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.foldRight(payload, function(curr, prev) curr * prev, 1)
------------------------
.Result
------------------------
24
/*
  4 * 1 = 4 // 1 in this case is the initial value
  3 * 4 = 12
  2 * 12 = 24
  1 * 24 = 24
*/
------------------------

### `groupBy(array|object items, function discriminator)`
Groups the provided `items` into an object based on the result of `discriminator`.

The function `discriminator` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
{
  "languages": [
    {
      "name": "Foo",
      "language": {
          "name": "Java",
          "version": "1.8"
      }
    },
    {
      "name": "Bar",
      "language": {
          "name": "Scala",
          "version": "1.0"
      }
    },
    {
      "name": "FooBar",
      "language": {
          "name": "Java",
          "version": "1.7"
      }
    }
  ]
}
----------
.DataSonnet map:
------------------------
{
  languageGroups: ds.groupBy(payload.languages, function(value, index) value.language.name)
}
------------------------
.Result
------------------------
{
    "languageGroups": {
       "Java": [
          {
             "language": {
                "name": "Java",
                "version": "1.8"
             },
             "name": "Foo"
          },
          {
             "language": {
                "name": "Java",
                "version": "1.7"
             },
             "name": "FooBar"
          }
       ],
       "Scala": [
          {
             "language": {
                "name": "Scala",
                "version": "1.0"
             },
             "name": "Bar"
          }
       ]
    }
}
------------------------

### `isArray(any valToCheck)`
Accepts any given value as `valToCheck` and checks if it is of type array.

*Example*

.Payload
----------
[
    1,
    2,
    3,
    4
]
----------
.DataSonnet map:
------------------------
ds.isArray(payload)
------------------------
.Result
------------------------
true
------------------------

### `isBlank(string strToCheck)`
Checks if `strToCheck` is blank. Also returns true if null.

*Example*

.Payload
----------
{
   "airlineName": ""
}
----------
.DataSonnet map:
------------------------
ds.isBlank(payload.airlineName)
------------------------
.Result
------------------------
true
------------------------

### `isBoolean(any valToCheck)`
Accepts any given value as `valToCheck` and checks if it is of type bool.

*Example*

.Payload
----------
{
  "name": "Java",
  "isObjectOriented": true
}
----------
.DataSonnet map:
------------------------
ds.isBoolean(payload.isObjectOriented)
------------------------
.Result
------------------------
true
------------------------

### `isDecimal(num numToCheck)`
Checks that the input number `numToCheck` is a decimal number. Trailing zeros do not count.

*Example*

.Payload
----------
{
  "name": "Java",
  "version": 1.8
}
----------
.DataSonnet map:
------------------------
ds.isDecimal(payload.version)
------------------------
.Result
------------------------
true
------------------------

### `isEmpty(any valToCheck)`
Checks if `valToCheck` is empty. Does not ignore white space if string. Returns true if null.

*Example*

.Payload
----------
[]
----------
.DataSonnet map:
------------------------
ds.isEmpty(payload)
------------------------
.Result
------------------------
true
------------------------

### `isEven(num numToCheck)`
Checks that the input number `numToCheck` is an even number.

*Example*

.Payload
----------
{
    "version": 2.0
}
----------
.DataSonnet map:
------------------------
ds.isEven(payload.version)
------------------------
.Result
------------------------
true
------------------------

### `isFunction(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type function.

*Example*

.DataSonnet map:
------------------------
ds.isFunction(function() "5")
------------------------
.Result
------------------------
true
------------------------

### `isInteger(num numToCheck)`
Checks that the input number `numToCheck` is an integer.
The number passed drops trailing zeros, so `2.0` would be `true`
but `2.1` would be `false`.

*Example*

.Payload
----------
{
    "version": 2.0
}
----------
.DataSonnet map:
------------------------
ds.isInteger(payload.version)
------------------------
.Result
------------------------
true
------------------------

### `isNumber(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type number.

*Example*

.Payload
----------
{
    "age": 5
}
----------
.DataSonnet map:
------------------------
ds.isNumber(payload.age)
------------------------
.Result
------------------------
true
------------------------

### `isObject(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type object.

*Example*

.Payload
----------
{
    "language": "Java"
}
----------
.DataSonnet map:
------------------------
ds.isObject(payload)
------------------------
.Result
------------------------
true
------------------------

### `isOdd(num numToCheck)`
Checks that `numToCheck` is an odd number.

*Example*

.Payload
----------
{
    "age": 5
}
----------
.DataSonnet map:
------------------------
ds.isOdd(payload.age)
------------------------
.Result
------------------------
true
------------------------

### `isString(any valToCheck)`
Accepts any given value `valToCheck` and checks if it is of type string.

*Example*

.Payload
----------
{
    "language":"Java"
}
----------
.DataSonnet map:
------------------------
ds.isString(payload.language)
------------------------
.Result
------------------------
true
------------------------

### `joinBy(array arr, string separator)`
Joins `arr` into a string with the provided `separator`.

*Example*

.Payload
----------
{
    "versions": [1.0, 1.2, 1.7, 1.8]
}
----------
.DataSonnet map:
------------------------
ds.joinBy(payload.versions, ", ")
------------------------
.Result
------------------------
"1, 1.2, 1.7, 1.8"
------------------------

### `keysOf(object obj)`
Returns an array of all the key names in `obj`.

*Example*

.Payload
----------
{
   "departureDate": "01/20/2019",
   "origin": "PHX",
   "destination": "SEA"
 }
----------
.DataSonnet map:
------------------------
ds.keysOf(payload)
------------------------
.Result
------------------------
[
  "departureDate",
  "origin",
  "destination"
]
------------------------

### `lower(string str)`
Converts `str` to all lower case characters.

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
 }
----------
.DataSonnet map:
------------------------
ds.lower(payload.origin)
------------------------
.Result
------------------------
"phx"
------------------------

### `map(array arr, function func)`
Loops through all items in `arr`, applies `func` to each, and returns a new array containing each result. Returns null if `arr` is null.

The function `func` is expected to take the value as the first parameter (required) and the index as the second (optional).

*Example*

.Payload
----------
{
    "versions": [1.0, 1.2, 1.7, 1.8]
}
----------
.DataSonnet map:
------------------------
ds.map(payload.versions, function(value, index) value > 1.2)
------------------------
.Result
------------------------
[
  false,
  false,
  true,
  true
]
------------------------

### `mapEntries(object obj, function func)`
Loops through all properties in `obj`, applies `func` to each, and returns a new array containing each result.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
}
----------
.DataSonnet map:
------------------------
ds.mapEntries(payload, function(value, key, index) value)
------------------------
.Result
------------------------
[
  "PHX",
  "SEA"
]
------------------------

### `mapObject(object obj, function func)`
Loops through all properties in `obj`, applies `func` to each, and returns a new object containing each result.

The function `func` is expected to take the property value as the first parameter (required), the property key as the second (optional) and the index as the third (optional).

*Example*

.Payload
----------
{
   "origin": "PHX",
   "destination": "SEA"
}
----------
.DataSonnet map:
------------------------
ds.mapObject(payload, function(value, key, index) {[key]:value})
------------------------
.Result
------------------------
{
  "origin": "PHX",
  "destination": "SEA"
}
------------------------

### `match(string str, string regex)`
Executes the regex expression `regex` against `str` and returns an array with the match groups.

*Example*

.Payload
----------
{
    "email": "test@server.com"
}
----------
.DataSonnet map:
------------------------
ds.match(payload.email, "(.*)@(.*)(.com)")
------------------------
.Result
------------------------
[
  "test@server.com",
  "test",
  "server",
  ".com"
]
------------------------

### `matches(string str, string regex)`
Executes the regex expression `regex` against `str` and returns `true` or `false` if the expression matches the input.

*Example*

.Payload
----------
{
    "email": "test@server.com"
}
----------
.DataSonnet map:
------------------------
ds.matches(payload.email, "(.*)@(.*)(.com)")
------------------------
.Result
------------------------
true
------------------------

### `max(array arr)`
Returns the max value in `arr`.

*Example*

.Payload
----------
[
    5,
    2,
    7,
    3
]
----------
.DataSonnet map:
------------------------
ds.max(payload)
------------------------
.Result
------------------------
7
------------------------

### `maxBy(array arr, function func)`
Returns the max result of `func` in `arr`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.maxBy(payload, function(value) value.age)
------------------------
.Result
------------------------
{
  "age": 7
}
------------------------

### `min(array arr)`
Returns the min value in `arr`.

*Example*

.Payload
----------
[
    5,
    2,
    7,
    3
]
----------
.DataSonnet map:
------------------------
ds.min(payload)
------------------------
.Result
------------------------
2
------------------------

### `minBy(array arr, function func)`
Returns the max result of `func` in `arr`.

The function `func` is expected to take the value as the first parameter (required).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.minBy(payload, function(value) value.age)
------------------------
.Result
------------------------
{
  "age": 3
}
------------------------

### `orderBy(array|object arr, function func)`
Reorders the array `arr` by the result of `func`.

If `arr` is an array: the function `func` is expected to take the value as the first parameter (required).

If `arr` is an object: the function `func` is expected to take the value as the first parameter (required) and the key as the second parameter (optional).

*Example*

.Payload
----------
[
    {"age": 5},
    {"age": 7},
    {"age": 3}
]
----------
.DataSonnet map:
------------------------
ds.orderBy(payload, function(value) value.age)
------------------------
.Result
------------------------
[
  {
    "age": 3
  },
  {
    "age": 5
  },
  {
    "age": 7
  }
]
------------------------

### `remove(object obj, string propName)`
Removes property `propName` from `obj` and returns the remaining object.

*Example*

.Payload
----------
{
   "availableSeats": 45,
   "airlineName": "Delta",
   "aircraftBrand": "Boeing",
   "aircraftType": "717",
   "departureDate": "01/20/2019",
   "origin": "PHX",
   "destination": "SEA"
 }
----------
.DataSonnet map:
------------------------
ds.remove(payload, 'availableSeats')
------------------------
.Result
------------------------
{
   "airlineName": "Delta",
   "aircraftBrand": "Boeing",
   "aircraftType": "717",
   "departureDate": "01/20/2019",
   "origin": "PHX",
   "destination": "SEA"
 }
------------------------

### `reverse(array arr)`
Returns an array with elements of `arr` in reverse order.

*Example*

.Payload
----------
[
    "a",
    "b",
    "c",
    "d"
]
----------
.DataSonnet map:
------------------------
ds.reverse(payload)
------------------------
.Result
------------------------
[
    "d",
    "c",
    "b",
    "a",
]
------------------------

### `parseDouble(string str)`

Parses a string `str` which contains a double number and returns its numeric representation

*Example*

.Payload
----------
{
    "numberAsString": "123.45679"
}

----------
.DataSonnet map:
------------------------
{
    num: ds.parseDouble(payload.numberAsString)
}
------------------------
.Result
------------------------
{
    "num": 123.45679
}
------------------------

## crypto

### `hash(string value, string algorithm)`
Calculates hash of `value` using one of the supported algorithms. The `algorithm` must be one of `MD2`, `MD5`, `SHA-1`, `SHA-256`, `SHA-384`, `SHA-512`
The response is a string containing the hash bytes.

*Example:*

------------------------
{
    hashValue: ds.crypto.hash("HelloWorld", "MD5")
}
------------------------
.Result
------------------------
{
    "hashValue": "68e109f0f40ca72a15e05cc22786f8e6"
}
------------------------
### `hmac(string value, string secret, string algorithm)`
Generates hash-based message authentication code using provided `value`, `secret`, and a hash function `algorithm`. The `algorithm` must be one of `HmacSHA1`, `HmacSHA256` or `HmacSHA512`.

*Example:*

------------------------
{
    hmacValue: ds.crypto.hmac("HelloWorld", "DataSonnet rules!", "HmacSHA256")
}
------------------------
.Result
------------------------
{
    "hmacValue": "7854220ef827b07529509f68f391a80bf87fff328dbda140ed582520a1372dc1"
}
------------------------

## datetime

### `now()`
Returns the current date/time from the system UTC clock in ISO-8601 format.

*Example*

------------------------
{
    currentZuluTime: ds.datetime.now()
}
------------------------

.Result:
------------------------
{
    "currentZuluTime": "2019-08-19T18:58:38.313Z"
}
------------------------

### `format(string datetime, string inputFormat, string outputFormat)`
Reformats a zoned date-time string.

*Example*

------------------------
ds.datetime.format("2019-07-04T21:00:00Z", "yyyy-MM-dd'T'HH:mm:ssVV", "d MMM uuuu")
------------------------
.Result:
------------------------
4 Jul 2019
------------------------

### `compare(string datetime1, string format1, string datetime2, string format2)`
Returns `1` if `datetime1 > datetime2`, `-1` if `datetime1 < datetime2`, and `0` if `datetime1 == datetime2`.

*Example*

------------------------
ds.datetime.compare("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ", "2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result
------------------------
0
------------------------

### `changeTimeZone(string datetime, string format, string timezone)`
Changes the date timezone, retaining the instant. This normally results in a change to the local date-time.
The response is formatted using the same format as an input.

*Example*

------------------------
ds.datetime.changeTimeZone("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ", "America/Los_Angeles")
------------------------
.Result:
------------------------
2019-07-04T19:00:00-0700
------------------------

### `toLocalDate(string datetime, string format)`
Returns only local date part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalDate("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
2019-07-04
------------------------

### `toLocalTime(string datetime, string format)`
Returns only local time part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalTime("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
21:00:00
------------------------

### `toLocalDateTime(string datetime, string format)`
Returns local datetime part of the `datetime` parameter in the ISO-8601 format without the offset.

*Example*

------------------------
ds.datetime.toLocalDateTime("2019-07-04T21:00:00-0500", "yyyy-MM-dd'T'HH:mm:ssZ")
------------------------
.Result:
------------------------
2019-07-04T21:00:00
------------------------

## localdatetime

### `now()`
Returns the current date/time from the system UTC clock in ISO-8601 format without a time zone.

*Example*

------------------------
{
    currentLocalTime: ds.localdatetime.now()
}
------------------------

.Result:
------------------------
{
    "currentLocalTime": "2019-08-19T18:58:38.313"
}
------------------------

### `offset(string datetime, string period)`
Returns a copy of `datetime` with the specified amount added. The `datetime` parameter is in the ISO-8601 format without an offset.
The `period` is a string in the ISO-8601 period format.

*Example*

------------------------
ds.localdatetime.offset("2019-07-22T21:00:00", "P1Y1D")
------------------------
.Result:
------------------------
2020-07-23T21:00:00
------------------------

### `format(string datetime, string inputFormat, string outputFormat)`
Reformats a local date-time string.

*Example*

------------------------
ds.localdatetime.format("2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss", "d MMM uuuu")
------------------------
.Result:
------------------------
4 Jul 2019
------------------------

### `compare(string datetime1, string format1, string datetime2, string format2)`
Returns `1` if `datetime1 > datetime2`, `-1` if `datetime1 < datetime2`, and `0` if `datetime1 == datetime2`.
The `format1` and `format2` parameters must not have an offset or time zone.

*Example*

------------------------
ds.localdatetime.compare("2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss", "2019-07-04T21:00:00", "yyyy-MM-dd'T'HH:mm:ss")
------------------------
.Result:
------------------------
0
------------------------

## jsonpath

### `select(object json, string path)`

Evaluates JsonPath expression and returns the resulting JSON object.
It uses the https://github.com/json-path/JsonPath[Jayway JsonPath implementation] and fully supports https://goessner.net/articles/JsonPath/[JsonPath specification].

*Example*

.Payload
------------------------
{
  "store": {
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ]
  }
}
------------------------
.DataSonnet map:
------------------------
{
    author: ds.jsonpath.select(payload, "$..book[-2:]..author")[0]
}
------------------------
.Result
------------------------
{
    "author": "Herman Melville"
}
------------------------

## math

### `sum(array arr)`
Returns sum of all elements in `arr`.

*Example*

.Payload
----------
[ 10, 20, 30 ]
----------
.DataSonnet map:
------------------------
ds.math.sum(payload)
------------------------
.Result
------------------------
60
------------------------

### `round(double num, int precision)`
Rounds a double `num` to the number of digits after the decimal point.

*Example*

.Payload
----------
{
    "num": 123.562567558
}
----------
.DataSonnet map:
------------------------
ds.math.round(payload.num, 6)
------------------------
.Result
------------------------
123.562568
------------------------

## regex

### `regexFullMatch(string pattern, string input)`
Matches the entire input against the pattern (anchored start and end). If there's no match, returns `null`. If there's a match, returns a JSON object which has the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexFullMatch(@'h(?P<mid>.*)o', 'hello')
------------------------
.Result
------------------------
{
  "string": "hello",
  "captures": [
    "ell"
  ],
  "namedCaptures": {
    "mid": "ell"
  }
}
------------------------

### `regexPartialMatch(string pattern, string input)`
Matches the input against the pattern (unanchored). If there's no match, returns `null`. If there's a match, returns a JSON object which has the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexPartialMatch(@'e(?P<mid>.*)o', 'hello')
------------------------
.Result
------------------------
{
  "string": "ello",
  "captures": [
    "ll"
  ],
  "namedCaptures": {
    "mid": "ll"
  }
}
------------------------

### `regexScan(string pattern, string input)`
Finds all matches of the input against the pattern. If there are any matches, returns an array of JSON objects which have the following structure:

- `string` - the matched string;
- `captures` - array of captured subgroups in the match, if any;
- `namedCaptures` - map of named subgroups, if any;

*Example*

.DataSonnet map:
------------------------
ds.regex.regexScan(@'(?P<user>[a-z]*)@(?P<domain>[a-z]*).org', 'modus@datasonnet.org,box@datasonnet.org')
------------------------
.Result
------------------------
[
  {
    "string": "modus@datasonnet.org",
    "captures": [
      "modus",
      "datasonnet"
    ],
    "namedCaptures": {
      "domain": "datasonnet",
      "user": "modus"
    }
  },
  {
    "string": "box@datasonnet.org",
    "captures": [
      "box",
      "datasonnet"
    ],
    "namedCaptures": {
      "domain": "datasonnet",
      "user": "box"
    }
  }
]
------------------------

### `regexQuoteMeta(string str)`
Returns a literal pattern string for the specified string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexQuoteMeta(@'1.5-2.0?')
------------------------
.Result
------------------------
"1\\.5-2\\.0\\?"
------------------------

### `regexReplace(string str, string pattern, string replacement)`
Returns the input with the first match replaced by `replacement` string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexReplace('wishyfishyisishy', @'ish', 'and')
------------------------
.Result
------------------------
"wandyfishyisishy"
------------------------

### `regexGlobalReplace(string str, string pattern, string replacement)`
Returns the input with all matches replaced by `replacement` string.

*Example*

.DataSonnet map:
------------------------
ds.regex.regexGlobalReplace('wishyfishyisishy', @'ish', 'and')
------------------------
.Result
------------------------
"wandyfandyisandy"
------------------------

## url

### `encode(string data, string encoding="UTF-8")`

Translates a string into `application/x-www-form-urlencoded` format using the supplied encoding scheme to obtain the bytes for unsafe characters. The default encoding is `UTF-8`.

*Example*

.DataSonnet map:
------------------------
ds.url.encode('Hello World')
------------------------
.Result
------------------------
"Hello+World"
------------------------

### `decode(string data, string encoding="UTF-8")`

Decodes a application/x-www-form-urlencoded string using a specific encoding scheme. The supplied encoding is used to determine what characters are represented by any consecutive sequences of the form "%xy".

*Example*

.DataSonnet map:
------------------------
ds.url.decode('Hello+World')
------------------------
.Result
------------------------
"Hello World"
------------------------
