name: docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@v0.2.3
        with:
          antora_playbook: antora-playbook.yml
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/build/site"
  deploy_site:
    name: "Deploy GitHub Pages"
    runs-on: [ ubuntu-latest ]
    needs: [ build_site ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download generated site
        uses: actions/download-artifact@v1
        with:
          name: site
          path: "${{ github.workspace }}/site"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BRANCH: 'gh-pages'
          FOLDER: "site"
          COMMIT_MESSAGE: "[CI] Publish Documentation for ${{ github.sha }}"
          CLEAN: true
